// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz0pX9sVfx-sBmms-tbTR6aHN3_OMxqhM',
    appId: '1:337473087645:web:fc6f92f57401bdf7918c74',
    messagingSenderId: '337473087645',
    projectId: 'my-ecommerce-app-down',
    authDomain: 'my-ecommerce-app-down.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-down.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDabCHrHclwaRWPKQQYmsyMtmybp8A-q0',
    appId: '1:337473087645:android:9b8dd66e6fbaaf89918c74',
    messagingSenderId: '337473087645',
    projectId: 'my-ecommerce-app-down',
    storageBucket: 'my-ecommerce-app-down.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz0pX9sVfx-sBmms-tbTR6aHN3_OMxqhM',
    appId: '1:337473087645:web:21947c136bfa0e70918c74',
    messagingSenderId: '337473087645',
    projectId: 'my-ecommerce-app-down',
    authDomain: 'my-ecommerce-app-down.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-down.firebasestorage.app',
  );
}